### ISSUE TITLE
Support Embedding of the Frontend

### ISSUE THREAD

**Issue by OhmSpectator** [OhmSpectator/track-your-regions#45]
Support embedding the frontend React application into the backend Node.js service. This will allow us to deploy a single Docker container that serves both the frontend and backend, while still retaining the option to run them as separate containers.

1. Update Docker Compose File: Modify the `docker-compose.yml` to include a named volume for holding the frontend build files and mount it in the backend service.

```yaml
volumes:
frontend-build:
```

```yaml
frontend:
volumes:
- frontend-build:/usr/src/app/build
```

```yaml
backend:
volumes:
- frontend-build:/usr/src/app/public
```

2. Update Backend Code: Modify the backend's `app.js` to serve the static frontend files from the mounted directory.

```javascript
app.use(express.static('/usr/src/app/public'));
```

Add `depends_on`: Ensure the backend service depends on the frontend service being built first.

```yaml
backend:
depends_on:
- frontend
```

3. Update Makefile: Add a new target in the Makefile to run the Docker Compose setup.

```makefile
start-embedded:
$(DC) up --build
```
